name: Windows and MacOS - Build

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # Uncomment above to auto-build and release on pushes to main

jobs:
  build-for-desktop:
    name: Build for ${{ matrix.targetPlatform }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform:
          - StandaloneWindows64
          - StandaloneOSX
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - name: Build project
        uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          buildName: Fruit66
      - name: Zip output
        run: |
          cd ./build/${{ matrix.targetPlatform }}
          zip -r ../../Fruit66.${{ matrix.targetPlatform }}.zip .
      - uses: actions/upload-artifact@v3
        with:
          name: Fruit66.${{ matrix.targetPlatform }}.zip
          path: Fruit66.${{ matrix.targetPlatform }}.zip
  create-release:
    name: Upload and create new release
    needs: build-for-desktop
    runs-on: ubuntu-latest
    steps:
      - name: Create environment variables
        run: |
          date="$(date +"%Y-%m-%d")"
          tag="Release_${{ github.run_number }}_$date"
          echo "date=$date" >> $GITHUB_ENV
          echo "tag=$tag" >> $GITHUB_ENV
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: "Release #${{ github.run_number }} ${{ env.date }}"
          tag_name: ${{ env.tag }}
          files: artifacts/**/*.*
          generate_release_notes: true
